// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: pkg/gRPC/event.proto

package gRPC

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EventClient is the client API for Event service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventClient interface {
	AfterCreate(ctx context.Context, in *OnCreate, opts ...grpc.CallOption) (*Response, error)
	BeforeShutDown(ctx context.Context, in *OnShutDown, opts ...grpc.CallOption) (*Response, error)
	HealthCheck(ctx context.Context, in *OnHealthCheck, opts ...grpc.CallOption) (*Response, error)
	GetInstances(ctx context.Context, in *RoleData, opts ...grpc.CallOption) (*Instances, error)
}

type eventClient struct {
	cc grpc.ClientConnInterface
}

func NewEventClient(cc grpc.ClientConnInterface) EventClient {
	return &eventClient{cc}
}

func (c *eventClient) AfterCreate(ctx context.Context, in *OnCreate, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/gRPC.Event/AfterCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventClient) BeforeShutDown(ctx context.Context, in *OnShutDown, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/gRPC.Event/BeforeShutDown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventClient) HealthCheck(ctx context.Context, in *OnHealthCheck, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/gRPC.Event/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventClient) GetInstances(ctx context.Context, in *RoleData, opts ...grpc.CallOption) (*Instances, error) {
	out := new(Instances)
	err := c.cc.Invoke(ctx, "/gRPC.Event/GetInstances", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServer is the server API for Event service.
// All implementations must embed UnimplementedEventServer
// for forward compatibility
type EventServer interface {
	AfterCreate(context.Context, *OnCreate) (*Response, error)
	BeforeShutDown(context.Context, *OnShutDown) (*Response, error)
	HealthCheck(context.Context, *OnHealthCheck) (*Response, error)
	GetInstances(context.Context, *RoleData) (*Instances, error)
	mustEmbedUnimplementedEventServer()
}

// UnimplementedEventServer must be embedded to have forward compatible implementations.
type UnimplementedEventServer struct {
}

func (UnimplementedEventServer) AfterCreate(context.Context, *OnCreate) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AfterCreate not implemented")
}
func (UnimplementedEventServer) BeforeShutDown(context.Context, *OnShutDown) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BeforeShutDown not implemented")
}
func (UnimplementedEventServer) HealthCheck(context.Context, *OnHealthCheck) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedEventServer) GetInstances(context.Context, *RoleData) (*Instances, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInstances not implemented")
}
func (UnimplementedEventServer) mustEmbedUnimplementedEventServer() {}

// UnsafeEventServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventServer will
// result in compilation errors.
type UnsafeEventServer interface {
	mustEmbedUnimplementedEventServer()
}

func RegisterEventServer(s grpc.ServiceRegistrar, srv EventServer) {
	s.RegisterService(&Event_ServiceDesc, srv)
}

func _Event_AfterCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnCreate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServer).AfterCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gRPC.Event/AfterCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServer).AfterCreate(ctx, req.(*OnCreate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Event_BeforeShutDown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnShutDown)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServer).BeforeShutDown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gRPC.Event/BeforeShutDown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServer).BeforeShutDown(ctx, req.(*OnShutDown))
	}
	return interceptor(ctx, in, info, handler)
}

func _Event_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnHealthCheck)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gRPC.Event/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServer).HealthCheck(ctx, req.(*OnHealthCheck))
	}
	return interceptor(ctx, in, info, handler)
}

func _Event_GetInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServer).GetInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gRPC.Event/GetInstances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServer).GetInstances(ctx, req.(*RoleData))
	}
	return interceptor(ctx, in, info, handler)
}

// Event_ServiceDesc is the grpc.ServiceDesc for Event service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Event_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gRPC.Event",
	HandlerType: (*EventServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AfterCreate",
			Handler:    _Event_AfterCreate_Handler,
		},
		{
			MethodName: "BeforeShutDown",
			Handler:    _Event_BeforeShutDown_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _Event_HealthCheck_Handler,
		},
		{
			MethodName: "GetInstances",
			Handler:    _Event_GetInstances_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/gRPC/event.proto",
}
